### PR TITLE
Add an example for converting gltf to inputs.

### PR DESCRIPTION
**Pull request by fire**
Hi @lucidrains I added an example of converting gltf2 to your example in the readme.

~~This is without the sorting strategy.~~

image

Let me know what to do with this.

### CODE REVIEW

**Comment by fire** [comment]
Do you know if the triangles are deduplicated outside meshgpt? They're currently disconnected.

**Comment by fire** [comment]
Theres currently a bug where some faces are disconnected. I needed to sleep on it.

**Comment by MarcusLoppe** [comment]
You don't need the angles/area/normal's. They are used when embedding the face and automatically calculated using get_derived_face_features function. You only need to provide the vertices (xyz) and faces (indices to vertices array).

```
 @beartype
    def encode(
        self,
        *,
        vertices:         TensorType['b', 'nv', 3, float],
        faces:            TensorType['b', 'nf', 3, int],
        face_edges:       TensorType['b', 'e', 2, int],
        face_mask:        TensorType['b', 'nf', bool],
        face_edges_mask:  TensorType['b', 'e', bool],
        return_face_coordinates = False
    ):
        """
        einops:
        b - batch
        nf - number of faces
        nv - number of vertices (3)
        c - coordinates (3)
        d - embed dim
        """

        batch, num_vertices, num_coors, device = *vertices.shape, vertices.device
        _, num_faces, _ = faces.shape

        face_without_pad = faces.masked_fill(~rearrange(face_mask, 'b nf -> b nf 1'), 0)

        faces_vertices = repeat(face_without_pad, 'b nf nv -> b nf nv c', c = num_coors)
        vertices = repeat(vertices, 'b nv c -> b nf nv c', nf = num_faces)

        # continuous face coords

        face_coords = vertices.gather(-2, faces_vertices)

        # compute derived features and embed

        derived_features = get_derived_face_features(face_coords)

        discrete_angles = self.discretize_angles(derived_features['angles'])
        angle_embed = self.angle_embed(discrete_angles)

        discrete_area = self.discretize_area(derived_features['area'])
        area_embed = self.area_embed(discrete_area)

        discrete_normal = self.discretize_normals(derived_features['normals'])
        normal_embed = self.normal_embed(discrete_normal)```

**Comment by lucidrains** [comment]
> Theres currently a bug where some faces are disconnected. I needed to sleep on it.

can confirm sleeping on a problem is the best way to solve them :)

**Comment by lucidrains** [comment]
@fire so one suggestion is to modularized this into a `GLTFDataset`, extending the pytorch `Dataset`, receiving the folder of 3d shape files and outputting the `vertices` and `faces` as a tuple. then it can just be plugged into the trainer [here](https://github.com/lucidrains/meshgpt-pytorch/blob/main/meshgpt_pytorch/trainer.py#L330)

**Comment by fire** [comment]
Do we care about when the artist has modified the normals since that's not geometrically correct?

**Comment by fire** [comment]
image

I'll stop here. Hopefully I'll get more time next weekend.

**Comment by fire** [comment]
I removed the normals codes.

**Comment by fire** [comment]
What is a pytorch Dataset? I assume its like a binary jsonl? I’ll have to take a look. Then we can investigate translation, rotation and scale of objects.

**Comment by fire** [comment]
@lucidrains Let me know if this GLTFDataset is proper?

**Comment by fire** [comment]
How do I plug this into the trainer? @lucidrains

**Comment by lucidrains** [comment]
@fire if you have a function that turns a `.gltf` file into the `vertices` and `faces`, i can craft a dataset function creator that accepts this function and creates the dataset that you plug into the trainer [here](https://github.com/lucidrains/meshgpt-pytorch/blob/main/meshgpt_pytorch/trainer.py#L106)

**Comment by lucidrains** [comment]
@fire knowing nothing about 3d data, can you confirm that you have a pile of `.gltf` files to learn on?

**Comment by fire** [comment]
https://huggingface.co/datasets/allenai/objaverse-xl here is the pile

**Comment by lucidrains** [comment]
@fire is it all `.gltf` files?

**Comment by lucidrains** [comment]
@fire ok, let me switch gears and knock this out for you in the next half hour

**Comment by lucidrains** [comment]
example with mock dataset (it should run)

```python
import torch

from meshgpt_pytorch import (
    MeshAutoencoder,
    MeshAutoencoderTrainer,
)

# autoencoder

autoencoder = MeshAutoencoder(
    dim = 512,
    encoder_depth = 6,
    decoder_depth = 6,
    num_discrete_coors = 128
)

# mock dataset

from torch.utils.data import Dataset

class MockDataset(Dataset):
    def __init__(self):
        pass

    def __len__(self):
        return 100

    def __getitem__(self, idx):
        from random import randrange
        return torch.randn(randrange(100, 121), 3), torch.randint(0, 121, (randrange(61, 96), 3))

# autoencoder trainer

trainer = MeshAutoencoderTrainer(
    autoencoder,
    dataset = MockDataset(),
    batch_size = 2,
    grad_accum_every = 2,
    num_train_steps = 3,
    checkpoint_every = 1
)

trainer()
```

**Comment by lucidrains** [comment]
but what i'll also accept (to be built in the next half hour)

```python
MeshAutoencoderTrainer(
   folder = '/path/to/3d-shapes',
   file_to_3d_transforms = dict(
       gltf = gltf_to_3d_fn,
       glb = gltf_to_3d_fn,
       ...
   )
)
```

**Comment by fire** [comment]
Question, the arrays are sorted per primitive, because I got stuck on merging the sub meshes index wise. I think it’ll be fine for the auto encoder though. The shape is different and not flattened because I wasn’t able to round trip it. Let me know if this is a problem

**Comment by lucidrains** [comment]
ihavenoidea

all i really know is the residual VQ + attention portions. that's all i can claim to be an expert on

**Comment by lucidrains** [comment]
ok try the latest version

just showing a mock function as an example

```python
from meshgpt_pytorch import DatasetFromTransforms

dataset = DatasetFromTransforms(
    folder = './folder_with_gltf_files',
    transforms = dict(
        gltf = lambda t: (torch.randn(100, 3), torch.randint(0, 3, (60, 3)))
    )
)

trainer = MeshAutoencoderTrainer(
    autoencoder,
    dataset = dataset,
    batch_size = 2,
    grad_accum_every = 2,
    num_train_steps = 3,
    checkpoint_every = 1
)

```

**Comment by fire** [comment]
I think my arrays is in [[p0, p1, p2],…]] and  [[f0, f1, f2], […]] form. So we might need another for loop

**Comment by lucidrains** [comment]
```python
from mesh_pytorch import DatasetFromTransforms

dataset = DatasetFromTransforms(
    folder = './your/folder/with/3d/assets',
    transforms = dict(gltf = your_function)
)
```

**Comment by fire** [comment]
I currently do:

```
dataset = GLTFDataset("unit_test")
mesh_00 = dataset.__getitem__(0)
print(mesh_00)
```

```json
([(2.625437021255493, -1.0, 1.0), (2.625437021255493, -1.0, 1.0), (2.625437021255493, -1.0, 1.0), (2.625437021255493, 1.0, 1.0), (2.625437021255493, 1.0, 1.0), (2.625437021255493, 1.0, 1.0), (2.625437021255493, -1.0, -1.0), (2.625437021255493, -1.0, -1.0), (2.625437021255493, -1.0, -1.0), (2.625437021255493, 1.0, -1.0), (2.625437021255493, 1.0, -1.0), (2.625437021255493, 1.0, -1.0), (4.625437021255493, -1.0, 1.0), (4.625437021255493, -1.0, 1.0), (4.625437021255493, -1.0, 1.0), (4.625437021255493, 1.0, 1.0), (4.625437021255493, 1.0, 1.0), (4.625437021255493, 1.0, 1.0), (4.625437021255493, -1.0, -1.0), (4.625437021255493, -1.0, -1.0), (4.625437021255493, -1.0, -1.0), (4.625437021255493, 1.0, -1.0), (4.625437021255493, 1.0, -1.0), (4.625437021255493, 1.0, -1.0), (-2.0182169257803615, 2.5430066658662263, 0.9467812917345272), (-2.0182169257803615, 2.5430066658662263, 0.9467812917345272), (-2.0182169257803615, 2.5430066658662263, 0.9467812917345272), (-2.2360159615003505, 1.2905272178401987, 1.1773736974601008), (-2.2360159615003505, 1.2905272178401987, 1.1773736974601008), (-2.2360159615003505, 1.2905272178401987, 1.1773736974601008), (-1.7084187659764165, 2.133268964034903, -0.9861284619477502), (-1.7084187659764165, 2.133268964034903, -0.9861284619477502), (-1.7084187659764165, 2.133268964034903, -0.9861284619477502), (-1.9262178016964056, 0.880789516008876, -0.7555360562221767), (-1.9262178016964056, 0.880789516008876, -0.7555360562221767), (-1.9262178016964056, 0.880789516008876, -0.7555360562221767), (-0.0713326858219051, 2.2724621319403426, 1.3161691791431667), (-0.0713326858219051, 2.2724621319403426, 1.3161691791431667), (-0.0713326858219051, 2.2724621319403426, 1.3161691791431667), (-0.28913172154189404, 1.0199826839143156, 1.5467615848687402), (-0.28913172154189404, 1.0199826839143156, 1.5467615848687402), (-0.28913172154189404, 1.0199826839143156, 1.5467615848687402), (0.23846547398204, 1.86272443010902, -0.6167405745391108), (0.23846547398204, 1.86272443010902, -0.6167405745391108), (0.23846547398204, 1.86272443010902, -0.6167405745391108), (0.020666438262051168, 0.6102449820829926, -0.3861481688135372), (0.020666438262051168, 0.6102449820829926, -0.3861481688135372), (0.020666438262051168, 0.6102449820829926, -0.3861481688135372)], [[8, 20, 14], [8, 14, 2], [8, 11, 23], [8, 23, 20], [20, 23, 17], [20, 17, 14], [2, 11, 8], [2, 5, 11], [14, 5, 2], [14, 17, 5], [47, 35, 32], [35, 29, 26], [23, 11, 5], [23, 5, 17], [41, 47, 44], [41, 29, 47], [29, 35, 47], [29, 41, 38], [44, 47, 32], [32, 35, 26], [38, 41, 44], [38, 44, 32], [26, 29, 38], [26, 38, 32]])```

**Comment by lucidrains** [comment]
@fire lgtm!

**Comment by fire** [comment]
Any idea what is going wrong?

```powershell
meshgpt-pytorch> python .\trainer.py
loss: 5.813
Traceback (most recent call last):
  File "C:\Users\ernes\Downloads\meshgpt-pytorch\trainer.py", line 30, in <module>
    trainer()
  File "C:\Users\ernes\scoop\apps\python310\current\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\ernes\scoop\apps\python310\current\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ernes\Downloads\meshgpt-pytorch\meshgpt_pytorch\trainer.py", line 293, in forward
    self.log(loss = loss.item())
  File "C:\Users\ernes\Downloads\meshgpt-pytorch\meshgpt_pytorch\trainer.py", line 211, in log
    self.accelerator.log(data_kwargs, step = self.step.item())
  File "C:\Users\ernes\scoop\apps\python310\current\lib\site-packages\accelerate\accelerator.py", line 615, in _inner
    return PartialState().on_main_process(function)(*args, **kwargs)
  File "C:\Users\ernes\scoop\apps\python310\current\lib\site-packages\accelerate\accelerator.py", line 2479, in log
    for tracker in self.trackers:
AttributeError: 'Accelerator' object has no attribute 'trackers'
```

**Comment by fire** [comment]
The trainer.py script seems to work. I tested with some characters which were too slow and a furniture folder. 

Let me know how to use the trained function, I'm curious.

**Comment by fire** [comment]
I tested with the code in this branch and it's training. I have to go for today, but you can check the git history for my changes.

```powershell
meshgpt-pytorch> python .\trainer.py
loss: 5.734
loss: 5.988
```

**Comment by fire** [comment]
As of [03582fa](https://github.com/lucidrains/meshgpt-pytorch/pull/6/commits/03582fa3e5fc3cfab3951d3e37cc06c655d0c501) loss seems to decrease which is amazing.

**Comment by lucidrains** [comment]
> As of [03582fa](https://github.com/lucidrains/meshgpt-pytorch/pull/6/commits/03582fa3e5fc3cfab3951d3e37cc06c655d0c501) loss seems to decrease which is amazing.

loss goes down, dopamine goes up

that's life being a deep learning practitioner

**Comment by fire** [comment]
I have a GLTFDataset I want to test. How do I do that with the auto encoder? I want to load it into blender to check.

**Comment by lucidrains** [comment]
is gltf the most popular format for meshes?

**Comment by fire** [comment]
FBX, GLTF, and USD are for the modt populsr for scenes. STL,OBJ and ply are popular too but for example these can be in rotated in 6 arbitrary ways which makes it hard to define a unified format. The rest of the formats trail off significantly.

Note that implementing FBX and USD from scratch is expensive due to complexity.

**Comment by fire** [comment]
The count in the 10 million count data set roughly matches popularity

**Comment by fire** [comment]
image

**Comment by lucidrains** [comment]
🙄 that's a lot of file formats

please standardize more kthnxbai

**Comment by fire** [comment]
Theres an xkcd about 14 standards.. Also we can convert all of these to gltf, we don't care about materials.

**Comment by lucidrains** [comment]
@fire is gltf your perferred format? it doesn't seem like the most popular from the statistics you show

**Comment by lucidrains** [comment]
indeed, i know that xkcd comic! lol

**Comment by fire** [comment]
Here's a more detailed summary.

| fileType | count   | category     | comments                                                                                                                                                                           |
| -------- | ------- | ------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| stl      | 4317074 | Mesh Format  | STL is a widely used mesh format, commonly used for 3D printing models. However, it lacks an unambiguous top position ordering required by MeshGPT.                                        |
| obj      | 1620091 | Mesh Format  | OBJ is another popular mesh format often used for 3D graphics. It also lacks an unambiguous top position ordering required by MeshGPT and has wide support in 3D graphics software.         |
| fbx      | 1509719 | Scene Format | FBX is the most popular scene format but creating an FBX importer is non-trivial. It's widely used in the film industry and game development for its versatility.                  |
| gltf/glb | 1112411 | Scene Format | GLTF/GLB are open standard scene formats developed by the Khronos Group. They are designed for efficient loading and interoperability across platforms.                            |
| ply      | 839343  | Mesh Format  | PLY is a mesh format commonly used in 3D scanning systems. Like STL and OBJ, it lacks an unambiguous top position ordering required by MeshGPT.                                             |
| blend    | 238201  | Scene Format | BLEND is the native format of Blender, a popular open-source 3D modeling software. Creating a BLEND importer would require understanding the Blender system, which can be complex. |
| dae      | 123438  | Scene Format | DAE (Collada) is an interchange file format for interactive 3D applications. It's managed by the Khronos Group. However, it is not an active standard.                                      |
| usdz     | 5681    | Scene Format | USDZ is a variation of the USD 3D file format used in Apple's ARKit. It's optimized for sharing in apps like Messages, Safari, and Mail. Creating an USDZ importer can be complex. |
| abc      | 1053    | Scene Format | ABC (Alembic) is an open computer graphics interchange framework. It's commonly used in the VFX industry for exchanging complex animated scenes. This is the least common format.  |

**Comment by fire** [comment]
Supporting all the available formats could increase MeshGpt compatibility and reach, but it also presents challenges.

Importing FBX files requires a copy of Maya, costing $2000 to $3000 per year, due to the complexity of handling these files in Blender.

Similarly, USDZ files may require standalone tools like Apple's Reality Converter, which might not support all file features.

The DAE format lacks standardization, complicating consistent results across platforms or software.

However, integrating Blender support is feasible and has been demonstrated by @MarcusLoppe. Blender could potentially import the remaining formats. However, it means that Blender would be part of the Dataset importer class which would make embedding the entire MeshGPT system into a game engine more difficult.

**Comment by fire** [comment]
@lucidrains Let me know how you want me to contribute the GLTFDataset code into the main repo. I can create a new pull request.

**Pull request closed without merging**
