### PR TITLE
Add experimental softplus to LFQ to fix negative commit loss

### PR DESCRIPTION
**Pull request by avramdj**
[Negative commit loss](https://github.com/lucidrains/meshgpt-pytorch/issues/43) fix based on recommendation from the [similar issue in LFQ](https://github.com/lucidrains/vector-quantize-pytorch/issues/92#issuecomment-2178900135)

### CODE REVIEW

**Comment by lucidrains** [comment]
@avramdj hey Avram, thanks for this PR

have you tested this, does it work well with it turned on by default?

also, what is your interest in meshgpt? for personal use or for some startup / company?

**Comment by lucidrains** [comment]
@avramdj the negative commit loss isn't an issue btw, just kind of disconcerting to look at

**Comment by avramdj** [comment]
> @avramdj hey Avram, thanks for this PR
> 
> have you tested this, does it work well with it turned on by default?
> 
> also, what is your interest in meshgpt? for personal use or for some startup / company?

Yup I've tested it out on a private dataset and it fixes the issue. It's too early to tell but it looks like recon loss is pretty much the same. 

But I wonder what the practical impacts of negative commit loss could be. Doesn't it affect training stability?

**Comment by lucidrains** [comment]
@avramdj nevermind, it turns out i use the `x-transformers` `Decoder`, so it was an easy add

no worries, i know you startups keep your cards close. just shoot me a Signal with your results, if you can

**Comment by lucidrains** [comment]
go make the holodeck happen :wink:

**Pull request merged**
